# Generated by Django 3.1.8 on 2021-04-19 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('condition', models.CharField(choices=[('bn', 'Brand-new'), ('sh', 'Second-hand')], default='bn', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('pic1', models.ImageField(upload_to='product_pics')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('street', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField(default=234)),
                ('whatsapp', models.IntegerField(default=234)),
                ('site', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='shop_pics')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('school', models.ManyToManyField(to='market.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('charge', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='service_pics')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='service_pics')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='service_pics')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='service_pics')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='service_pics')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.school')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.shop')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=18)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('dp', models.ImageField(null=True, upload_to='review_dp')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='review_pics')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='review_pics')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='review_pics')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='review_pics')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='review_pics')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='review_pics')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.service')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('ref_pic', models.ImageField(blank=True, null=True, upload_to='request_pics')),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.school'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.shop'),
        ),
    ]
