# Generated by Django 3.1.8 on 2021-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('RSU', 'Rivers State University')], default='bn', max_length=20),
        ),
    ]
