# Generated by Django 3.1.8 on 2021-04-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210420_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=60)),
                ('typ', models.CharField(choices=[('RSU', 'Rivers State University')], max_length=20)),
                ('price', models.IntegerField()),
                ('school', models.CharField(choices=[('RSU', 'Rivers State University')], max_length=20)),
                ('pic1', models.ImageField(upload_to='product_pics')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='product_pics')),
            ],
        ),
    ]
